# Generated by Django 4.0.5 on 2022-07-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color_productvariation_size_remove_variation_product'),
        ('carts', '0004_alter_cartitem_variations'),
        ('orders', '0002_alter_orderproduct_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
    ]
