# Generated by Django 4.0.5 on 2022-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='ip',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
