# Generated by Django 4.0.5 on 2022-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreview_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
