# Generated by Django 4.0.5 on 2022-07-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color_productvariation_size_remove_variation_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariation'),
        ),
    ]
